services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: project2-jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      DOCKER_HOST: "tcp://dind:2375"  # point to DIND container
    networks:
      - jenkins-net

  dind:
    image: docker:dind
    container_name: project2-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge

